"""
Domain schemas — the single source of truth for the shape of data that
crosses the frontend/backend boundary. These mirror `frontend/lib/types.ts`
on purpose: the Next.js API client types are generated by hand to match
these one-for-one, so a change here is a deliberate, visible contract
change, not an accidental drift.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field

# --- Identity / access -------------------------------------------------------

AccountType = Literal["employee", "administrator"]
PrivilegeLevel = Literal["standard", "team_lead", "manager"]
Role = Literal["employee", "team_lead", "manager", "administrator"]

Department = Literal[
    "Sales", "Operations", "Finance", "Engineering", "Customer Success", "Marketing", "HR"
]


class Identity(BaseModel):
    """The caller's effective identity for this request. In production this
    is derived from a verified Microsoft Entra ID token; in mock mode it is
    read from demo headers (see app/core/identity.py)."""

    account_type: AccountType
    employee_id: Optional[str] = None
    display_name: str
    title: str
    role: Role


# --- Employees ----------------------------------------------------------------


class Employee(BaseModel):
    id: str
    name: str
    title: str
    department: Department
    manager_id: Optional[str] = None
    email: str
    avatar_color: str
    response_score: int
    median_response_minutes: int
    answered_within_24h_pct: int
    positive_communication_pct: int
    overdue_follow_ups: int
    open_commitments: int
    sla_compliance_pct: int


# --- Communications -----------------------------------------------------------

CommClassification = Literal["customer", "vendor", "internal"]
ResponseStatus = Literal["needs_response", "waiting", "completed", "overdue"]
Priority = Literal["low", "normal", "high", "critical"]
AIReviewStatus = Literal["pending", "confirmed", "dismissed", "needs_context"]


class TimelineEvent(BaseModel):
    id: str
    label: str
    timestamp: str
    actor: str


class AIFinding(BaseModel):
    id: str
    response_required: bool
    priority: Priority
    ownership: str
    commitment_detected: bool
    due_date: Optional[str] = None
    next_action: str
    quality_score: int
    confidence_pct: int
    review_status: AIReviewStatus
    reasoning: str


class Communication(BaseModel):
    id: str
    contact: str
    organization: str
    category: CommClassification
    subject: str
    body_preview: str
    received_at: str
    responded_at: Optional[str] = None
    response_time_minutes: Optional[int] = None
    status: ResponseStatus
    priority: Priority
    owner_id: str
    next_step: str
    quality_score: int
    ai_finding: Optional[AIFinding] = None
    timeline: list[TimelineEvent] = Field(default_factory=list)
    excluded: bool = False
    exclusion_reason: Optional[str] = None


# --- Commitments / follow-ups / alerts -----------------------------------------

CommitmentStatus = Literal["active", "due_today", "due_this_week", "overdue", "completed"]


class Commitment(BaseModel):
    id: str
    title: str
    source: str
    owner_id: str
    created_at: str
    due_date: str
    status: CommitmentStatus
    days_overdue: int
    next_action: str


class CommitmentCreate(BaseModel):
    """Input for creating a commitment — e.g. from the Outlook add-in's
    'Add commitment' action on a message, or a future web dashboard form.
    `owner_id` defaults to the caller's own employee id; a manager/admin
    may set it explicitly for someone they're authorized to view."""

    title: str
    source: str
    due_date: str
    next_action: str = "Send update to contact and close loop"
    owner_id: Optional[str] = None


FollowUpStatus = Literal["open", "overdue", "due_today", "completed", "escalated"]


class FollowUp(BaseModel):
    id: str
    contact: str
    subject: str
    owner_id: str
    due_date: str
    status: FollowUpStatus
    last_activity: str
    next_action: str


AlertCategory = Literal[
    "needs_response", "overdue", "commitment", "follow_up", "ai_coaching", "positive_indicator"
]
AlertSeverity = Literal["low", "medium", "high"]


class AlertItem(BaseModel):
    id: str
    category: AlertCategory
    severity: AlertSeverity
    time: str
    source: str
    reason: str
    recommended_action: str
    owner_id: str


# --- Customers ------------------------------------------------------------------

CustomerHealth = Literal["strong", "steady", "at_risk"]


class Customer(BaseModel):
    id: str
    name: str
    industry: str
    open_communications: int
    avg_response_minutes: int
    outstanding_commitments: int
    follow_ups: int
    health: CustomerHealth


# --- Reviews / evidence / audit --------------------------------------------------

ReviewStatus = Literal["pending_review", "confirmed", "dismissed", "needs_context"]


class Review(BaseModel):
    id: str
    employee_id: str
    finding: str
    evidence: str
    ai_confidence_pct: int
    status: ReviewStatus
    reviewer: Optional[str] = None
    date: str
    communication_id: str


EvidenceResult = Literal["confirmed", "excluded", "under_review"]


class Evidence(BaseModel):
    id: str
    finding: str
    source: str
    date: str
    rule: str
    evidence_text: str
    context: Optional[str] = None
    result: EvidenceResult


class AuditEntry(BaseModel):
    id: str
    timestamp: str
    user: str
    action: str
    resource: str
    result: Literal["success", "denied"]
    ip: str


# --- AI coaching insights ------------------------------------------------------

InsightKind = Literal["strength", "improve", "follow_through", "response", "positive"]


class AIInsight(BaseModel):
    id: str
    employee_id: str
    kind: InsightKind
    headline: str
    why: str
    evidence: str
    confidence_pct: int
    review_status: Literal["unreviewed", "reviewed"]


# --- Dashboard (the "Communication Effectiveness" home page) -------------------


class MetricStat(BaseModel):
    label: str
    value: float
    suffix: Optional[str] = None
    trend: Literal["up", "down", "flat"]
    trend_label: str
    progress_pct: float
    source: Optional[str] = None


class TrendWeek(BaseModel):
    label: str
    employee: int
    team: int


class ReviewPoint(BaseModel):
    title: str
    desc: str


class PerformanceReviewSummary(BaseModel):
    overall_label: str
    delta_points: int
    filled_dots: int
    total_dots: int = 7
    strengths: list[ReviewPoint]
    coaching: list[ReviewPoint]


class CommitmentRow(BaseModel):
    category: str
    within_sla_pct: int
    within_sla_numerator: int
    within_sla_denominator: int
    overdue: int
    trend: Literal["up", "down", "flat"]
    bold: bool = False


class QualityMeter(BaseModel):
    label: str
    sub: str
    pct: int
    color: str


class DashboardEvidenceItem(BaseModel):
    id: str
    title: str
    date: str
    quote: str
    tag: str
    positive: bool
    ai_note: Optional[str] = None


class DashboardAlert(BaseModel):
    id: str
    severity: AlertSeverity
    title: str
    subject: str
    sender: str = Field(alias="from")
    preview: str
    meta: str
    action: str

    model_config = {"populate_by_name": True}


class ExcludedMessage(BaseModel):
    subject: str
    sender: str = Field(alias="from")
    reason: str

    model_config = {"populate_by_name": True}


class DashboardView(BaseModel):
    """Everything the Home / Communication Effectiveness page needs for one
    person's (or the org's) dashboard — one call, one round trip."""

    scope_label: str
    scope_subtitle: str
    metrics: list[MetricStat]
    overdue_open: int
    trend: list[TrendWeek]
    weeks_above_goal: str
    review_summary: PerformanceReviewSummary
    commitment_rows: list[CommitmentRow]
    quality_meters: list[QualityMeter]
    evidence_items: list[DashboardEvidenceItem]
    alerts: list[DashboardAlert]
    excluded_messages: list[ExcludedMessage]


class RosterEmployee(BaseModel):
    """Row shown in the Manager View team roster before a person is selected."""

    id: str
    name: str
    title: str
    department: Department
    avatar_color: str
    response_score: int
    overdue_follow_ups: int


# --- Settings -------------------------------------------------------------------


class ScoringRule(BaseModel):
    id: str
    label: str
    value: str


class ExclusionRule(BaseModel):
    id: str
    label: str
    description: str
    rule: str
    enabled: bool


class IntegrationStatus(BaseModel):
    name: str
    status: Literal["connected", "not_configured", "mock_mode", "error"]
    description: str


class PermissionGrant(BaseModel):
    employee_id: str
    privilege: PrivilegeLevel


# --- Common ----------------------------------------------------------------------


class ApiError(BaseModel):
    code: str
    message: str
    request_id: Optional[str] = None


class ErrorEnvelope(BaseModel):
    error: ApiError
